# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pr.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import message
from google.protobuf import reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08pr.proto\x12\x11TestTask.Messages\"\x9c\x02\n\x0eWrapperMessage\x12\x36\n\rfast_response\x18\x01 \x01(\x0b\x32\x1f.TestTask.Messages.FastResponse\x12\x36\n\rslow_response\x18\x02 \x01(\x0b\x32\x1f.TestTask.Messages.SlowResponse\x12L\n\x19request_for_fast_response\x18\x03 \x01(\x0b\x32).TestTask.Messages.RequestForFastResponse\x12L\n\x19request_for_slow_response\x18\x04 \x01(\x0b\x32).TestTask.Messages.RequestForSlowResponse\")\n\x0c\x46\x61stResponse\x12\x19\n\x11\x63urrent_date_time\x18\x01 \x02(\t\".\n\x0cSlowResponse\x12\x1e\n\x16\x63onnected_client_count\x18\x01 \x02(\r\"\x18\n\x16RequestForFastResponse\":\n\x16RequestForSlowResponse\x12 \n\x18time_in_seconds_to_sleep\x18\x01 \x02(\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pr_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_WRAPPERMESSAGE']._serialized_start=32
  _globals['_WRAPPERMESSAGE']._serialized_end=316
  _globals['_FASTRESPONSE']._serialized_start=318
  _globals['_FASTRESPONSE']._serialized_end=359
  _globals['_SLOWRESPONSE']._serialized_start=361
  _globals['_SLOWRESPONSE']._serialized_end=407
  _globals['_REQUESTFORFASTRESPONSE']._serialized_start=409
  _globals['_REQUESTFORFASTRESPONSE']._serialized_end=433
  _globals['_REQUESTFORSLOWRESPONSE']._serialized_start=435
  _globals['_REQUESTFORSLOWRESPONSE']._serialized_end=493
# @@protoc_insertion_point(module_scope)


class WrapperMessage(_builder._message.Message, metaclass=_builder._reflection.GeneratedProtocolMessageType):
    DESCRIPTOR = _globals["_WRAPPERMESSAGE"]


class FastResponse(_builder._message.Message, metaclass=_builder._reflection.GeneratedProtocolMessageType):
    DESCRIPTOR = _globals["_FASTRESPONSE"]


class SlowResponse(_builder._message.Message, metaclass=_builder._reflection.GeneratedProtocolMessageType):
    DESCRIPTOR = _globals["_SLOWRESPONSE"]


class RequestForFastResponse(_builder._message.Message, metaclass=_builder._reflection.GeneratedProtocolMessageType):
    DESCRIPTOR = _globals["_REQUESTFORFASTRESPONSE"]


class RequestForSlowResponse(_builder._message.Message, metaclass=_builder._reflection.GeneratedProtocolMessageType):
    DESCRIPTOR = _globals["_REQUESTFORSLOWRESPONSE"]

